// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ApplicationCore.Entities;
using Microsoft.EntityFrameworkCore;
using System.Reflection;
#nullable disable

namespace Infrastructure.Data;

public partial class progwebContext : DbContext
{
    public progwebContext(DbContextOptions<progwebContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Usuario> Usuario { get; set; }
    public virtual DbSet<Comanda> Comanda { get; set; }
    public virtual DbSet<ComandaItem> ComandaItem { get; set; }
    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
